name: model_wine_quality_classification
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Install requirements
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r data_governance_hw/requirements.txt
      - name: Run black
        run: |
          black data_governance_hw/train.py
      - name: Run Pylint
        run: |
          python data_governance_hw/lint.py --path data_governance_hw/train.py --threshold 7
      - name: Run pipline
        run: |
          python data_governance_hw/train.py
          echo "## MODEL METRICS:" >> data_governance_hw/report.md
          cat metrics.txt >> data_governance_hw/report.md
          
          echo "## DATA VISUALIZATION:" >> data_governance_hw/report.md
          cml-publish data_governance_hw/lgbm_importances.png --md >> data_governance_hw/report.md
          
          cml-send-comment data_governance_hw/report.md
